version: '2'

services:
        app:
                image: digitalshoestring/user_input_dc:v1.1.7
                working_dir: /app
                command: sh -c "python manage.py collectstatic --noinput &&
                                python manage.py migrate &&
                                daphne -b 0.0.0.0 -p 80 manual_job_input.asgi:application"
                volumes:
                        - ./data/:/app/data
                        - /etc/localtime:/etc/localtime:ro
                ports:
                        - "8003:80"
