version: '2'

services:
        app:
                image: digitalshoestring/job_locations_sds:v1.1.7
                working_dir: /app
                command: sh -c "python manage.py collectstatic --noinput &&
                                python manage.py migrate &&
                                daphne -b 0.0.0.0 -p 80 job_locations.asgi:application"
                volumes:
                        - ./data/:/app/data
                        - ./config/:/app/config
                        - /etc/localtime:/etc/localtime:ro
                ports:
                        - "8001:80"
                restart: unless-stopped
