version: '2'

services:
        app:
            image: digitalshoestring/operator_ui:v1.1.7
            working_dir: /app
            command: sh -c "python manage.py collectstatic --noinput &&
                            python manage.py migrate &&
                            daphne -b 0.0.0.0 -p 80 operator_portal.asgi:application"
            volumes:
                    - ./data/:/app/data
                    - /etc/localtime:/etc/localtime:ro
            ports:
                    - "8080:80"
